parameters:
- name: UseYarn
  displayName: 'Use Yarn for Package Management?'
  type: boolean
  default: true

name: Build and Deploy Github Pages Files
on:
  push:
    branches:
      - master
      - WeighIns
  pull_request:
    branches:
      - master
      - WeighIns

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node 18
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install angular
      run: npm install -g @angular/cli    

    - name: Install Package Manager
      if ${{ eq(parameters.UseYarn, true) }}:
      run: echo 'true'

    - name: Install yarn
      run: yarn install

    - name: Install packages
      run: yarn;

    - name: Build Static Website Files
      run: node build.js

    # - name: Deploy
    #   uses: JamesIves/github-pages-deploy-action@4.1.4
    #   with:
    #     branch: gh-pages
    #     folder: docs
    #     target-folder: docs
