name: Build and Deploy Github Pages Files

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install angular
      run: npm install -g @angular/cli    

    - name: Install yarn
      run: yarn install

    - name: Install packages
      run: yarn;

    - name: Build
      run: ng build --prod --output-path docs --base-href "/chatAngular/"