name: Build and Deploy Github Pages Files
on:
  push:
    branches:
      - master
      - WeighIns
  pull_request:
    branches:
      - master
      - WeighIns

jobs:
  build:

    runs-on: ubuntu-20.04
    environment: production

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node 18
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install angular
      run: npm install -g @angular/cli    

    - name: Install yarn
      if: ${{ env.PACKAGE_MANAGER_NAME == 'YARN' }}
      run: yarn install

    - name: Install packages with yarn
      if: ${{ env.PACKAGE_MANAGER_NAME == 'YARN' }}
      run: yarn

    - name: Install packages with npm
      if: ${{ env.PACKAGE_MANAGER_NAME != 'YARN' }}
      run: npm install

    - name: Build Static Website Files
      run: node build.js

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: docs/test
        target-folder: docs/test
